# Generated by Django 5.0.6 on 2024-05-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True, null=True)),
                ('camion', models.CharField(max_length=50, null=True)),
                ('intento', models.IntegerField(default=0)),
                ('entrgado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Resumen_Despacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_venta', models.IntegerField()),
                ('id_despacho', models.IntegerField()),
            ],
        ),
    ]
