# Generated by Django 5.0.6 on 2024-05-10 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente_camion', models.CharField(max_length=6, null=True)),
                ('conductor', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='despacho',
            name='camion',
        ),
        migrations.AddField(
            model_name='despacho',
            name='patente_camion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.camion'),
        ),
    ]
