# Generated by Django 5.0.6 on 2024-05-10 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_camion_table_alter_despacho_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='camion',
            table='Camiones',
        ),
    ]
