# Generated by Django 5.0.6 on 2024-05-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_camion_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despacho',
            name='fecha',
            field=models.DateField(null=True),
        ),
    ]
