# Generated by Django 5.0.6 on 2024-05-12 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_despacho_fecha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='despacho',
            old_name='entrgado',
            new_name='entregado',
        ),
    ]
