# Generated by Django 5.0.6 on 2024-05-12 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_entrgado_despacho_entregado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camion',
            name='patente_camion',
            field=models.CharField(max_length=6, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='despacho',
            name='patente_camion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.camion', to_field='patente_camion'),
        ),
    ]
