# Generated by Django 5.0.6 on 2024-05-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_camion_patente_camion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='despacho',
            old_name='fecha',
            new_name='fecha_despacho',
        ),
        migrations.AddField(
            model_name='despacho',
            name='direccion_compra',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='despacho',
            name='id_compra',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='despacho',
            name='valor_compra',
            field=models.IntegerField(null=True),
        ),
    ]
