# Generated by Django 4.1.2 on 2024-05-15 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_fecha_despacho_fecha_despacho_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despacho',
            name='patente_camion',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.DeleteModel(
            name='Camion',
        ),
    ]
