# Generated by Django 4.1.2 on 2024-05-15 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_despacho_patente_camion_delete_camion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despacho',
            name='entregado',
            field=models.BooleanField(null=True),
        ),
    ]
