# Generated by Django 5.0.6 on 2025-04-02 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_despacho_entregado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion_compra', models.CharField(max_length=50, null=True)),
                ('valor_compra', models.IntegerField(null=True)),
                ('fecha_compra', models.DateField(null=True)),
                ('despacho_generado', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Ventas',
            },
        ),
    ]
